/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mctech.Forms;

/**
 *
 * @author anderson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        M_home = new javax.swing.JMenu();
        M_add = new javax.swing.JMenu();
        M_add_clientes = new javax.swing.JMenuItem();
        M_add_func = new javax.swing.JMenuItem();
        M_add_proc = new javax.swing.JMenuItem();
        M_busca = new javax.swing.JMenu();
        M_busca_clientes = new javax.swing.JMenuItem();
        M_busca_func = new javax.swing.JMenuItem();
        M_busca_proc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        M_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/home_2018_32.png"))); // NOI18N
        M_home.setText("Inicio");
        jMenuBar1.add(M_home);

        M_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/add_2018.png"))); // NOI18N
        M_add.setText("Adicionar");

        M_add_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/user_2018_32.png"))); // NOI18N
        M_add_clientes.setText("Clientes");
        M_add.add(M_add_clientes);

        M_add_func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/func_2018_32.png"))); // NOI18N
        M_add_func.setText("Funcionarios");
        M_add.add(M_add_func);

        M_add_proc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/proc_2018_32.png"))); // NOI18N
        M_add_proc.setText("Processos");
        M_add.add(M_add_proc);

        jMenuBar1.add(M_add);

        M_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/busca_2018_32.png"))); // NOI18N
        M_busca.setText("Consulta");

        M_busca_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/user_2018_32.png"))); // NOI18N
        M_busca_clientes.setText("Clientes");
        M_busca.add(M_busca_clientes);

        M_busca_func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/func_2018_32.png"))); // NOI18N
        M_busca_func.setText("Funcionarios");
        M_busca.add(M_busca_func);

        M_busca_proc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/proc_2018_32.png"))); // NOI18N
        M_busca_proc.setText("Processos");
        M_busca.add(M_busca_proc);

        jMenuBar1.add(M_busca);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/atalho_2018_32.png"))); // NOI18N
        jMenu3.setText("Atalhos");
        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctech/imagens/conf_2018_32.png"))); // NOI18N
        jMenu5.setText("Configurações");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu M_add;
    private javax.swing.JMenuItem M_add_clientes;
    private javax.swing.JMenuItem M_add_func;
    private javax.swing.JMenuItem M_add_proc;
    private javax.swing.JMenu M_busca;
    private javax.swing.JMenuItem M_busca_clientes;
    private javax.swing.JMenuItem M_busca_func;
    private javax.swing.JMenuItem M_busca_proc;
    private javax.swing.JMenu M_home;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
